### ISSUE TITLE
Relese repo changed on a way to 1.0

### ISSUE THREAD

**Issue by jest** [osgi/workspace#5]
In commit c0520c130e1c4be7b769e6ce1209af1e48a842d2 the `-releaserepo` line was removed from `enroute.bnd`. This caused the (updated) workspace to forget about what was previously released to Release and offered to re-release everything into Local.

From the names of the repos it looks like the change was not deliberate, but an by-product of massive change, and the `-releaserepo` line should be reintroduced.

**Comment by pkriens** [comment]
You're right. Fixed.
